### ISSUE TITLE
Cryptocat is an inactive project.

### ISSUE THREAD

**Issue by seamustuohy** [pippinlee/open-journalism-project#34]
Cryptocat is mentioned in the security section under [examples and code](https://github.com/pippinlee/open-journalism-project/blob/gh-pages/security.md#examples-and-code)  This tool has been [shut down by its creator](http://web.archive.org/web/20160222145547/https://crypto.cat/) while he developed a new version. This section should be updated to either mention that it is currently offline or should have the cryptocat portion removed.

**Comment by pippinlee** [comment]
Thanks @elationfoundation 👍

Let's hope there's a new desktop Cryptocat soon.
